### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by senhas-rgb** [SadeveM/Password-Generator#1]
![image](https://github.com/user-attachments/assets/dac9f5d9-fd27-44fd-b01f-8c41d1305b63)
Site not working with the hosting service used. Might be easy to use inbuilt github pages to host the site???

**Comment by SadeveM** [comment]
I added an alternate link to visit the site. 
Link: https://sadevem.github.io/Password-Generator/
Thank you for pointing out the error.
