### ISSUE TITLE
Uncaught TypeError: generateBtn is null

### ISSUE THREAD

**Issue by senhas-rgb** [SadeveM/Password-Generator#4]
Generating of password is not currently working when hosting locally for some reason.
Fetched these info from the browser console;
![image](https://github.com/user-attachments/assets/c195a6c5-5aeb-4f58-ab03-0e1ca8d7f3a7)
Browser info;
![image](https://github.com/user-attachments/assets/5b158664-9a85-456c-9270-db083956011b)
OS info;
Operating System: Pop!_OS 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 6.9.3-76060903-generic (64-bit)
Graphics Platform: X11

**Comment by SadeveM** [comment]
Pls confirm if you are viewing the site from your forked copy, if so it is possible that this error is due to the id changes u made for the generate button which might not have been updated in the javascript query selector for the generate button.

**Comment by senhas-rgb** [comment]
Thanks it might be due to local hosting.
